성적관리 [STEP 1] vapor.park
yagom-academy/ios-grade-manager pull request #2
Opened 2021-12-28 07:01 UTC by gustn3965

# STEP 1 

# 고민한 점 
* 테스트코드도 가능한 입력기능 구현 고민 
    *  `readLine`으로 입력받는 기능을 테스트코드에서는 `readLine`을 이용하지 않으면서 별도로 입력값을 주고자 했었다.
    *  테스트 성공여부를 확인하기 위하여, 부득이하게 메소드 반환에 `Bool` `return`값을 추가했고, `test`를 위한 매개변수도 메소드에 추가했다. 
    *  메소드 구현 코드만 본다면 갑자기 상관없는 매개변수 및 `return`값이 있어서 가독성에는 좋지 않는 듯 하다. 
    * 하지만 테스트코드를 작성할 수 있어서 장점도 있는 듯 하다.

* switch 문으로 분기 처리 
    * 성적관리 첫번째 메뉴 입력값의 가능한 값이 `1`,`2`,`3`,`4`,`5`, `X` 인데 이것을 switch 구문으로 분기처리한 것이 좋은 방법인지 잘 모르겠다.
    * switch 구문으로 인하여 메소드 10줄 이내 rule을 위반하게 됐다. 하지만 코드 가독성은 나쁘지 않다라고 생각했고, 더 좋은 방법은 떠오르지 않았다.

# 구현 방법
* `main` 
    * 프로그램이 동작하기 위한 코드 
* `Storage` 
    * STEP 1에서 학생추가 및 삭제를 담당할 수 있는 객체 
* `ScoreManager` 
    * 성적관리 앱의 핵심으로, 전반적인 플로우를 담당한다. 
    * `Storage`를 내부적으로 가지고 있으며, 이를 이용하여 사용자에게 학생추가 및 삭제를 보여주도록 한다. 
    * `isExit` 변수를 가지고 있으며, 이를 이용하여 무한루프를 종료하고자 한다. 
        * 기본적으로 무한 질문을 돌고 있으며, 사용자가 종료할 때만 무한 루프가 종료된다.

2021-12-28 13:39 UTC, zdodev requested changes
안녕하세요. @gustn3965!
첫 번째 프로젝트, 첫 번째 PR 축하합니다~

테스트를 작성하시고, 테스트를 고려하여 코드를 구현하신 점이 인상깊었습니다!
파일 분리도 적절하게 해주신 점도 좋았습니다!

이와 관련해서 다양한 의견을 남겨보았습니다. 
궁금하신 점이 있다면 같이 의견을 나눠보면 좋겠습니다.🤗

2021-12-28 13:39 UTC, zdodev commented on AddStudentTests/AddStudentTests.swift
> +        XCTAssertEqual(students.first!, student)
테스트에서도 강제 언래핑을 사용하는 것보다는 안전하게 옵셔널 바인딩을 통해서 테스트 코드를 작성해보는 것은 어떨까요? 테스트 코드도 구현 코드만큼 안전성이 중요하지 않을까 싶습니다!

2021-12-28 13:39 UTC, zdodev commented on AddStudentTests/AddStudentTests.swift
> +class AddStudentTests: XCTestCase {
테스트 코드까지 작성해보셨네요! 좋습니다.😎
다만 프로젝트에서 하나의 테스트 클래스마다 타겟을 생성하여 여러 테스트 타겟을 생성하셨는데 특별한 이유가 있을까요?🤔

2021-12-28 13:39 UTC, zdodev commented on AddStudentTests/AddStudentTests.swift
> +    func test_if_you_add_student_when_storage_has_same_student_then_you_cant_add() {
중복 입력에 대한 테스트 좋습니다!

2021-12-28 13:39 UTC, zdodev commented on DeleteStudentTests/DeleteStudentTests.swift
> +    func test_if_you_add_new_student_and_you_delete_that_student_then_it_should_be_deleted() {
입력과 삭제에 대한 테스트 좋습니다!

2021-12-28 13:39 UTC, zdodev commented on FilterSelectionMenu/CheckFirstMenuInput.swift
> +    func test_if_input_is_notNumber_AND_notX_than_return_false() {
입력 값에 대한 테스트 좋습니다!

2021-12-28 13:39 UTC, zdodev commented on GradeManager/ScoreManager.swift
> +}
사용 기능에 대한 메뉴 타입을 구현해주셨네요. 다만 `FirstMenu`, 첫 번째 메뉴라는 타입명이 불명확해보일 수 있다는 생각이 들어요. 조금 더 메뉴 리스트에 맞는 이름으로 변경해 볼 수 있을까요?🤔

2021-12-28 13:39 UTC, zdodev commented on GradeManager/ScoreManager.swift
> +    var errorDescription: String? {
`errorDescription`의 반환 타입을 옵셔널로 선언한 이유가 있을까요? 궁금합니다!

2021-12-28 13:39 UTC, zdodev commented on GradeManager/ScoreManager.swift
> +        while isExit == false {
`!isExit`는 어떨까요? `isExit == false` 표현도 좋아요! 의견이 궁금합니다.😁

2021-12-28 13:39 UTC, zdodev commented on GradeManager/ScoreManager.swift
> +    }
`read` 함수의 본연의 목적이 흐려지고 테스트를 작성하기 위한 코드를 작성하지 않았을까 싶습니다. 나중에 `testInput` 파라미터 명을 봤을 때 명확하기 이해하기 어려울 것 같습니다. 사용자에게 입력을 받을 수 있는 역할을 명확히 할 수 있는 코드로 작성해보는 것은 어떨까요? 이에 대해 의견이 있으시면 언제든지 말씀해주세요!😁

2021-12-28 13:39 UTC, zdodev commented on GradeManager/ScoreManager.swift
> +                                         withTestInput testInput: String? = nil) -> Bool {
마찬가지로 나중에 `testInput` 파라미터 명을 보았을 때, 어떤 역할을 하는지 이해하기 쉽지 않을 것 같습니다. 조금 더 역할에 맞는 이름으로 변경해보는 것은 어떨까요?🤔

2021-12-28 13:39 UTC, zdodev commented on GradeManager/ScoreManager.swift
> +        print(input + InputError.deleteStudentError.localizedDescription)
전체적으로 에러를 출력하기 위해 `print(input + InputError.Error.localizedDescription)` 형식을 사용하는데 단순히 print 함수만 보면 에러를 출력하기 위한 함수인지 이해하는 데 시간이 걸린다는 생각이 들었습니다. 에러를 출력하기 위한 메서드(함수)를 하나 생성해보는 것은 어떨까요?🤔

2021-12-28 13:39 UTC, zdodev commented on GradeManager/Storage.swift
> +struct Storage {
학생들을 관리하기 위해 Storage 타입을 구현하셨네요 좋습니다! 다만 어떤 `Storage`인지 구체적인 이름을 지어주면 더 좋을 것 같아요!

2021-12-28 13:39 UTC, zdodev commented on GradeManager/Storage.swift
> +    private var storage: [String: Int] = [:]
어떤 의미를 가지는 `storage` 일까요? `storage` 구조체 이름과 프로퍼티 명을 함께 고민해보면 좋을 것 같아요!

2021-12-28 13:39 UTC, zdodev commented on GradeManager/Storage.swift
> +        storage[student] = 5
`storage[student]`에 5를 대입하는 이유를 알 수 있을까요?🤔

2021-12-28 13:39 UTC, zdodev commented on GradeManager/Storage.swift
> +        let students = storage.keys.sorted(by: <)
클로저의 단축 표현을 잘 활용해주셨네요. 좋습니다!

2021-12-28 13:39 UTC, zdodev commented on GradeManager/ScoreManager.swift
> +    }
현재 주어진 6가지의 입력 값에 대해서 당장에는 나쁘다고 생각이 들지 않습니다. 추후에 입력 값이 늘어나면 다른 방법을 고민해보면 좋을 것 같습니다.

2021-12-29 06:24 UTC, gustn3965 commented on AddStudentTests/AddStudentTests.swift
> +class AddStudentTests: XCTestCase {
저도 Unit Test bundle 하나만 만들어서 그 안에 여러개의 테스트 파일을 작성하려고 했었는데요,
라이브 세션때 야곰님이 Unit Test Bundle 을 만드실 때, 이름을 테스트하고자 하는 이름으로 작성하신다고 하여, 여러개의 bundle로 만들게 됐습니다.

2021-12-29 06:25 UTC, gustn3965 commented on GradeManager/ScoreManager.swift
> +    var errorDescription: String? {
별 다른 이유는 없었습니다.  자동완성으로 String? 으로 만들어 주길래 그대로 사용했었습니다. 수정해보니 옵셔널이 아니여도 되는군요.  덕분에 알아갑니다. 감사합니다.

2021-12-29 06:28 UTC, gustn3965 commented on GradeManager/ScoreManager.swift
> +        while isExit == false {
저도 변수앞에 `!` 를 붙이는 걸 선호했었는데요, 같이 팀프로젝트 했던 iOS 분께서 변수 앞에 `!` 를 붙이는것 보다 `== false` 로 하는게 더 이해가 쉽다라고 하여 이렇게 쓰게 됐습니다. : )

2021-12-29 06:31 UTC, gustn3965 commented on GradeManager/Storage.swift
> +        storage[student] = 5
이부분은 더미값으로 우선 넣고자 했습니다. 추후 `STEP 2` 진행할 때 더 고려하려고 잠시 더미값으로 두었습니다.

2021-12-29 06:50 UTC, gustn3965 commented
@zdodev  

리뷰 감사드립니다. 

# 변경된 점 
리뷰 반영하면서 가장 고민한 점은, https://github.com/yagom-academy/ios-grade-manager/pull/2#discussion_r775912255 이 부분입니다.
가장 첫번째 메뉴에 해당하는 각 번호들을 공통된 `FirstMenu` 프로토콜을 채택하는 객체로 생성하여 각 메뉴에 해당하는 로직들을 구현했습니다. 
그리고 코멘트 주신 기존`switch`구문을 `FirstMenuFactory`의 `makeFirstMenu` 메소드를 이용하여 알맞는 객체들을 생성하도록 했습니다.
만약 이상한 값이 들어온다면 nil을 반환하도록 했습니다.
* 변경된 코드가 더 괜찮다라고 생각이 드는데, `switch` 구문까지 없애려고 더 고민을 해봤으나.. `switch` 구문자체를 없애는건 불가능하다고 생각이 됩니다. 혹시 더 좋은 생각이 있으신지요~?

# 제가 생각한 장점

그러다보니, 기존에 `ScoreManager`가 책임이 많다고 생각됐었는데, 좀 더 책임이 분할되었다고 생각합니다.

덕분에 테스트를 작성하기 위한 코드보다는 함수의 본연의 목적을 더 살리는 방향과도 부합이 됐다라고 생각합니다. ( https://github.com/yagom-academy/ios-grade-manager/pull/2#discussion_r775906211 )


------ 

이외의 내용은 소대님이 남기신 코멘트에 달아두었습니다. 감사합니다 ~

2021-12-29 11:50 UTC, zdodev requested changes
안녕하세요. @gustn3965 

전체적으로 코드가 많이 개선되었다고 생각이 듭니다.🤗
역할 분리를 보다 잘 나눠주셨습니다!

다만 현재 다음 스크린샷처럼 잘못된 에러 처리 기능이 잘 동작하지 않습니다.
<img width="902" alt="1" src="https://user-images.githubusercontent.com/67548251/147659276-334bb178-8bc0-401a-920f-2eb4d890c55e.png">

이 부분에 대한 수정이 필요하지 않을까 싶습니다!

남겨주신 질문에 대한 답변과 함께 피드백을 좀 남겨보았습니다.
궁금하신 점이 있다면 같이 의견을 나눠보면 좋겠습니다.😁

2021-12-29 11:50 UTC, zdodev commented on GradeManager/FirstMenu.swift
> +protocol FirstMenu {
메뉴에 대한 프로토콜을 구현하셨네요. 메뉴 별로 수행하는 행위를 `firstAction`으로 정의하신 점이 인상 깊습니다!🤩
메뉴가 늘어날 때마다 사용측 코드에서 유연하게 코드를 작성할 수 있다는 장점이 보입니다!

2021-12-29 11:50 UTC, zdodev commented on GradeManager/FirstMenu.swift
> +    var isExit: Bool { get set }
`isExit` 프로퍼티의 경우 외부에서 set을 해주는 상황이 보이지 않습니다. 외부에서 값을 변경하지 않는다면 `get` 속성만 사용해보는 것은 어떨까요?🤗

2021-12-29 11:50 UTC, zdodev commented on GradeManager/FirstMenu.swift
> +    mutating func firstAction()
메뉴가 수행할 행위를 나타내는 메서드라면 `action` 이라는 이름은 어떤가요?😁 `firstAction`은 행위의 순서를 강조하는 느낌이 들었습니다. 지금 이대로 작성하셔도 무방합니다.🤗

2021-12-29 11:50 UTC, zdodev commented on GradeManager/FirstMenu.swift
> +}
팩토리를 구현하셨네요.😲 질문에서 남겨주신 점에 대해서 이전보다 현재 코드가 더 개선되었다고 생각이 됩니다!
입력을 받는 경로가 단일 경로이기 때문에 `switch`문을 포함한 조건문, 분기문(`if`)을 안쓰고 구현하는 것은 상당히 힘들지 않을까 생각이 듭니다.
현재 주어진 입력 상황에서 다음과 같이 개선해주신 코드도 좋은 코드라고 생각이 됩니다. 좋습니다!👍

2021-12-29 11:50 UTC, zdodev commented on GradeManager/FirstMenu.swift
> +    var storage: ScoreStorage
`storage` 프로퍼티의 경우 `internal` 접근 제어를 사용하신 이유가 있을까요? 외부에 노출할 필요가 없는 프로퍼티라면 접근 제어 수준을 높여봐도 좋을 것 같습니다.😁

2021-12-29 11:50 UTC, zdodev commented on GradeManager/FirstMenu.swift
> +    mutating func addStudent() {
`addStudent` 메서드의 경우 `internal` 접근 제어를 사용하신 이유가 있을까요? 외부에 노출할 필요가 없는 메서드라면 접근 제어 수준을 높여봐도 좋을 것 같습니다.😁

2021-12-29 11:50 UTC, zdodev commented on GradeManager/FirstMenu.swift
> +        var errorMessage: String
에러 메시지 문자열을 표현하기 위한 프로퍼티 좋습니다!

2021-12-29 11:50 UTC, zdodev commented on GradeManager/FirstMenu.swift
> +    var storage: ScoreStorage
`storage` 프로퍼티의 경우 `internal` 접근 제어를 사용하신 이유가 있을까요? 외부에 노출할 필요가 없는 프로퍼티라면 접근 제어 수준을 높여봐도 좋을 것 같습니다.😁

2021-12-29 11:50 UTC, zdodev commented on GradeManager/FirstMenu.swift
> +    mutating func deleteStudent() {
`deleteStudent` 메서드의 경우 `internal` 접근 제어를 사용하신 이유가 있을까요? 외부에 노출할 필요가 없는 메서드라면 접근 제어 수준을 높여봐도 좋을 것 같습니다.😁

2021-12-29 11:50 UTC, zdodev commented on GradeManager/FirstMenu.swift
> +    var storage: ScoreStorage
`storage` 프로퍼티의 경우 `internal` 접근 제어를 사용하신 이유가 있을까요? 외부에 노출할 필요가 없는 프로퍼티라면 접근 제어 수준을 높여봐도 좋을 것 같습니다.😁

2021-12-29 11:50 UTC, zdodev commented on GradeManager/FirstMenu.swift
> +    mutating func exit() {
`exit` 메서드의 경우 `internal` 접근 제어를 사용하신 이유가 있을까요? 외부에 노출할 필요가 없는 메서드라면 접근 제어 수준을 높여봐도 좋을 것 같습니다.😁

2021-12-29 11:50 UTC, zdodev commented on GradeManager/ScoreManager.swift
> +enum FirstMenuList: String {
이름이 보다 명확해졌습니다. 좋습니다!

2021-12-29 11:50 UTC, zdodev commented on GradeManager/ScoreManager.swift
> +    }
문자열 출력하는 구문을 줄여보셨네요. 좋습니다!

2021-12-29 11:50 UTC, zdodev commented on GradeManager/ScoreStorage.swift
> +class ScoreStorage {
전보다 이름이 명확해졌습니다. 좋습니다!

2021-12-29 11:50 UTC, zdodev commented on GradeManager/ScoreStorage.swift
> +    private var studentsDict: [String: Int] = [:]
프로퍼티명을 변경해보셨네요. 좋습니다!

2021-12-29 11:54 UTC, zdodev commented on GradeManager/ScoreManager.swift
> +        while isExit == false {
자신의 의견을 남겨주셔서 감사합니다!

2021-12-30 01:50 UTC, gustn3965 commented
@zdodev 

두 번째 리뷰 감사드립니다!

리팩토링하면서 놓친 부분들이 있었네요.🥲 캐치해주셔서 감사합니다. 

# 반영한 점
첫번째 메뉴 목록이 나타날 때 1~5, X 이외의 값이 들어올 때 문구 표시. 
외부에서 사용하지 않는 메소드나 프로퍼티는 `private` 접근제어로 숨김 처리.

2021-12-30 02:05 UTC, zdodev approved these changes
안녕하세요! @gustn3965 

스텝1 기능에 대한 부분이 정상적으로 동작하는 것을 확인했습니다!
그리고 접근 제어 부분도 안전하게 수정해주셨네요.👍👍

스텝 1 구현하시느라 고생하셨습니다. 이번 스텝은 여기서 마무리 하겠습니다.
다음 스텝도 화이팅입니다!🥳

2021-12-30 02:05 UTC, zdodev commented on GradeManager/ScoreStorage.swift
> +final class ScoreStorage {
`final` 키워드를 사용해주셨네요.👍

2021-12-30 02:05 UTC, merged