성적관리 [STEP 1] liam
yagom-academy/ios-grade-manager pull request #3
Opened 2021-12-28 08:16 UTC by liam-777

안녕하세요. 성적관리 STEP1 PR 입니다! @wonhee009 

## 프로그램 개요

* `main.swift` 
프로그램을 동작시키기 위한 부분입니다.

* `GradeManager`
성적관리매니저 객체를 위한 struct입니다.
기능 부분들은 struct 선언부에 정의하였고 콘솔 관련 메서드들은 `extension`에 정의했습니다.

* `Student`
학생 정보를 저장할 struct입니다.
다음 기능(STEP2)을 구현할 때 성적과 관련된 프로퍼티들이 추가될 것이라고 생각되어서 미리 이름 기준으로만 비교할 수 있도록 ==를 오버라이딩 하였습니다.

* `StduentAdditionResult`, `StudentDelegationResult`
`GradeManager`의 학생 추가 기능(`addStudent(_:)`), 학생 삭제 기능(`deleteStudent(_:)`) 수행 시 반환되는 결과입니다.

* `GradeManagerTests`
유닛 테스트 코드 부분입니다.

## 코드를 작성할 때 고민되었던 점

**1.  열거형으로 함수 결과 Result 표현**

TDD에 맞춰 개발을 해보고자 노력했습니다. 그러다 보니깐 테스트를 하게 되는 작은 단위의 함수들까지 모두 반환 값을 필요로 했습니다. 

처음에는 true, false로 반환 값을 지정하고자 했는데 두 가지 값만 반환할 수 있는 Bool 타입으로 지정하자니 표현할 수 있는 케이스가 부족하고 정수 값으로 지정하자니 나중에 코드를 봤을 때 의미가 모호할 것 같아서 열거형으로 선언했습니다.

이 부분에서 Result를 나타내는 열거형들을 하나로 통일시키는 것이 맞는건지, 나누는 것이 맞는건지 고민을 해봤는데 의미상 다른 기능 수행에 대한 결과값이라서 나누어 작성했습니다.
`StudentAddtionResult`, `StudentDeletionResult`

**2.  enum의 associated value 네이밍**

enum의 case에 associated value를 네이밍할 때 `success(of:String)`, `success(with:String)`, `success(name:String)` 중에서 고민을 했습니다. associated value 네이밍의 결이 메서드 네이밍 보다는 생성자 또는 변수 네이밍에 더 가깝다고 생각이 들어서 `success(name:String)`으로 수정하였습니다.

**3. 사용자 입력 값을 가공하는 위치**

사용자 이름 입력에 대해서  무조건 시작 글자는 대문자, 이후 글자는 소문자로 변경해서 `Student` 객체를 저장하려 했습니다.
E.x : “mickEy” 를 입력해도 “Mickey”로 저장

저는 `Student` 생성자 안에서 반환하는게 맞나? 생각이 들긴 하는데 큰 프로그램에서 다른 사람의 코드를 파악해야 한다고 생각하면 이름을 받아오는 함수 안에서 변환해주는게 이해하기 좋겠다고 생각해서 일단은 `addStudent(_:)`, `deleteStudent(_:)` 안에서 수정했습니다.

사용자로부터 입력받은 문자열을 가공할 필요가 있을 때 이 시점이 어느 부분이 맞는 것인지 잘 모르겠습니다.

## 조언을 얻고 싶은 부분
* 위의 고민했던 부분들에 대해 궁굼합니다.
* 현재 커밋을 기능 단위로 나눠봤는데 이러한 사이즈가 맞는 것인지? 아니면 잘못 나눈 부분들이 있는지 궁궁합니다.

2021-12-28 11:13 UTC, wonhee009 requested changes
@liam-777 첫 프로젝트, 첫 스텝, 첫 PR 축하드립니다!🎉

각각의 역할을 나누려 노력한 흔적이 있는 코드라고 느껴졌습니다☺️
코드 관련해서 코멘트 남겨두었으니 확인해주시고 이해가 안 되거나 같이 의논하고 싶은 부부은 언제든 DM 보내주시면 감사하겠습니다😀

---

#### 1. 열거형으로 함수 결과 Result 표현

true, false 만으로는 표현할 수 있는 케이스가 부족하다고 적어주셨는데 저는 그럴 때 각각의 메서드가 본인이 맡은 일 **하나만**하고 있나 살펴보는 편입니다.
`addStudent(_ name: String?)`을 한 번 볼까요?
해당 메서드는 'name의 유효성 검사 -> 새로운 학생 생성 -> 중복 검사 -> 새로운 학생 insert -> 결과 반환'의 과정을 거치고 있습니다.
해당 메서드에서 분리할 수 있는 역할이 있지 않을까요?
예를 들어 addStudent를 호출할때 유효성 검사가 끝난 name을 사용한다면 해당 메서드는 `return true/false`만 사용할 수 있지 않을까요? 🤔

#### 2. enum의 associated value 네이밍

넵 적절하게 잘 사용하신거 같습니다👍

#### 3. 사용자 입력 값을 가공하는 위치

name을 가공하는 메서드를 하나 만드는건 어떨까요?
`addStudent()`나 `deleteStudent()`에서 공통적으로 사용하고 있고 입력 값을 가공하는 것도 하나의 책임이라고 생각하기 때문에 분리하는게 좋을거 같습니다☺️
또한, 테스트코드 작성 측면에서도 좋을거 같습니다.
현재 구조라면 `addStudent()`를 테스트한다면 'name 가공, student insert'를 확인해야하는데 name 가공이 분리된다면 테스트를 좀 더 잘게 챙겨갈 수 있을거 같습니다.

#### 커밋 단위

스펙을 추가할때 마다 커밋을 하고 계신거로 보이는데 적절하다 생각됩니다☺️

2021-12-28 11:13 UTC, wonhee009 commented on GradeManager/GradeManager.swift
> +struct GradeManager{
```suggestion
struct GradeManager {
```

2021-12-28 11:13 UTC, wonhee009 commented on GradeManager/GradeManager.swift
> +struct GradeManager{
[Swift 공식문서](https://docs.swift.org/swift-book/LanguageGuide/Functions.html)를 보면 
<img width="375" alt="image" src="https://user-images.githubusercontent.com/30456206/147550463-b426a4ab-269a-4d90-a78c-3e40a5be4ceb.png">
`{` 시작 전 한 칸씩 띄는걸 확인할 수 있습니다.👀

2021-12-28 11:13 UTC, wonhee009 commented on GradeManager/MenuInputValidationResult.swift
> +}
`-ValidationResult`에 `exit`가 있는게 어색한거 같아요.
유효성검사 결과에 관한 enum인데 `exit`는 메뉴 중 하나로 봐야하지 않을까요?🤔

2021-12-28 11:13 UTC, wonhee009 commented on GradeManager/Student.swift
> +struct Student: Hashable{
`Hashable`을 사용해보셨군요!👍

2021-12-28 11:13 UTC, wonhee009 commented on GradeManager/GradeManager.swift
> +        guard let input = input, !input.isEmpty else {
```swift
!input.isEmpty
```
같은 경우는 String extension을 이용해 `isNotEmpty`를 정의해서 사용하는 방법도 있습니다.
`!i` 이렇게 겹치면 눈에 잘 안 보이는 경우도 있더라구요👀

2021-12-28 11:13 UTC, wonhee009 commented on GradeManager/GradeManager.swift
> +        }
현재 스펙상 메뉴가 1~5여서 `1...5`를 사용하신거 같아요.
이후에 학생 추가 메뉴 번호가 6번으로 변경된다면 해당 코드들을 찾아서 변경해줘야 할거 같아요👀
이런 변경 사항들에 유연하게 대처할 수 있도록 해보는건 어떨까요?🤔

2021-12-28 11:13 UTC, wonhee009 commented on GradeManagerTests/GradeManagerTests.swift
> +
공백이 더 들어간거 같습니다.😀

2021-12-28 11:13 UTC, wonhee009 commented on GradeManagerTests/GradeManagerTests.swift
> +    }
" "인 경우도 추가되면 좋을거 같아요😀

2021-12-28 11:13 UTC, wonhee009 commented on GradeManagerTests/GradeManagerTests.swift
> +    func test_validateMenuNumber호출시_X를전달한경우_음수1을반환하는지(){
"음수1"보다는 "exit"는 어떤가요?🤔

2021-12-28 11:13 UTC, wonhee009 commented on GradeManagerTests/GradeManagerTests.swift
> +        XCTAssertEqual(result, .redundantName(name: "Micky"))
"Micky"를 하나의 변수로 관리하는 것도 좋을거 같아요😀

2021-12-28 11:13 UTC, wonhee009 commented on GradeManager/GradeManager.swift
> +struct GradeManager{
`GradeManager`를 struct로 정의한 이유가 있을까요?☺️
(struct로 정의하게 되면 `mutating`을 사용하게 되는데 이유가 궁금해서요.)

2021-12-28 11:13 UTC, wonhee009 commented on GradeManager/GradeManager.swift
> +        case 2: startStudentDeletion()
case 1, case 2를 보고 해당 숫자가 어떤 메뉴를 의미하는지 바로 알기 어려운거 같아요.
`case addStudent`처럼 숫자를 의미를 갖는 무언가로 만드는건 어떨까요?😀

2021-12-28 11:13 UTC, wonhee009 commented on GradeManager/GradeManager.swift
> +            print("1: 학생추가, 2: 학생삭제, 3: 성적추가(변경), 4: 성적삭제, 5: 평점보기, X: 종료")
```swift
let startMessage = """
원하는 기능을 입력해주세요.
1: 학생추가, 2: 학생삭제, 3: 성적추가(변경), 4: 성적삭제, 5: 평점보기, X: 종료
"""
```
이렇게 여러줄의 문자열도 표현 가능합니다☺️

2021-12-28 11:13 UTC, wonhee009 commented on GradeManager/GradeManager.swift
> +
```suggestion
```

2021-12-28 11:13 UTC, wonhee009 commented on GradeManager/GradeManager.swift
> +    }
`start`로 시작되는 네이밍을 사용하셨는데 이유가 있을까요?🤔

2021-12-29 06:22 UTC, liam-777 commented on GradeManagerTests/GradeManagerTests.swift
> +        XCTAssertEqual(result, .redundantName(name: "Micky"))
상세한 피드백 감사합니다 😃 
하나씩 수정해나가고 있는데 이 부분에서 궁굼한 점이 생겼습니다!

` var mickeyAsInputNameForTestCase: String = "Micky"`
우선 이런 식으로 따로 변수로 관리를 해봤습니다. 

    func test_addStudent호출시_영어숫자만이루어진문자열을전달하고_이미존재하는학생인경우_튜플_false_student_를반환하는지() {
        
        let mickey = Student(name: mickeyAsInputNameForTestCase)
        sut.students.insert(mickey)
        
        let result = sut.addStudent(mickeyAsInputNameForTestCase)
        
        XCTAssertFalse(result.0)
        XCTAssertEqual(result.1, mickey)
    }


그리고 테스트 코드를 위와 같이 수정했습니다.
결국에 기존 코드에서 "Mickey"는 하나의 변수로 관리되었지만, `let mickey = Student(name: mickeyAsInputNameForTestCase)` 이 부분에서 Student 객체를 다시 모든 코드에서 중복되게 정의하였습니다. 🥲

그러면 Student 객체를 또 변수로 관리해야 하나? 고민이 됐었는데요 .. 저는 중복을 줄이는 것도 중요하지만 테스트 코드에서 만큼은 given / when / then이 명확하게 나타나 있어야 가독성이 좋다고 생각이 들어서 given에 해당하는 부분이 중복되게 나온다고 해서 따로 변수로 관리하는 것이 맞는건지 의문이 드네요 ㅜㅜ

2021-12-29 06:29 UTC, wonhee009 commented on GradeManagerTests/GradeManagerTests.swift
> +        XCTAssertEqual(result, .redundantName(name: "Micky"))
아핫 이 부분은 제가 이유를 조금 생략해서 혼란이 있던거 같아요🥲
input이 "Micky"가 아니라 "Bob" 이렇게 수정할 경우에는 아래의 "Micky"를 일일이 바꿔줘야 하는 부분때문에 의견 드렸습니다.
하나의 변수로서 관리 한다면 변수값만 수정하면 되기 때문에 좀 더 수정에 열려 있는 테스트코드이지 않을까?해서 였습니다.

> 테스트 코드에서 만큼은 given / when / then이 명확하게 나타나 있어야 가독성이 좋다고 생각이 들어서

이 부분에 대해서는 저도 동감합니다☺️

2021-12-29 06:31 UTC, liam-777 commented on GradeManagerTests/GradeManagerTests.swift
> +        XCTAssertEqual(result, .redundantName(name: "Micky"))
아하 .. 감사합니다! 그 부분을 놓치고 있었네요 😮

2021-12-29 08:55 UTC, liam-777 commented on GradeManager/GradeManager.swift
> +struct GradeManager{
좋은 피드백 감사합니다 👍 이번 프로젝트에서는 별 생각 없이 본능적으로 사용했습니다 .. 반성하게 되네요.

 항상 struct와 class의 선택에 있어서 기준이 애매한 것 같습니다. struct가  값 복사나, 비교와 같은 상황에서 안전하고 침조사이클 같은 문제에서 자유롭다고 생각해서, 슈퍼 클래스로부터 상속이 필요하지 않는 상황 등 특정 상황이 아니면 그냥 구조체를 사용하는게 맞다고 생각했습니다.

 다시 고민해본 내용인데 피드백을 부탁드려도 될까요?

*  `GradeManager`  인스턴스는 다른 값과 비교, 복사할 상황이 없다.
  *  = reference로 접근하기 때문에 발생할 문제에 대해 고려할 필요가 없다.
*  오히려 mutating을 사용하게 되면 새로운 인스턴스를 다시 생성해서 할당하는꼴이 된다.
  * 학생 수가 많다면? 그 안의 추가될 성적의 양이 많다면? -> 많은 비용이 요구됨 
*  학생추가, 학생삭제, 성적추가, ... 모든 기능에서 mutating이 필요하기 때문에 class로 정의하는게 좋다

2021-12-29 09:50 UTC, liam-777 commented on GradeManager/GradeManager.swift
> +    }
시작의 의미로 작성했었는데 다시 보니 어색한 것 같네요. 

 `start` -> `startProgram`
 
 `startStudentAddition` -> `perfromStudentAddtionMenuAction` 

 이런 식으로 수정했는데 괜찮을까요?

2021-12-29 09:52 UTC, liam-777 commented on GradeManager/GradeManager.swift
> +        case 2: startStudentDeletion()
좋은 피드백 감사드립니다👍 enum으로 `GradeManagingMenu` 추가했습니다 !

2021-12-29 11:06 UTC, wonhee009 requested changes

2021-12-29 11:06 UTC, wonhee009 commented on GradeManager/Extension+String.swift
> +    }
`extension`을 적극적으로 사용해보셨군요👍

2021-12-29 11:06 UTC, wonhee009 commented on GradeManager/GradeManager.swift
> +        guard let input = input, !input.isEmpty else {
`isNotEmpty`를 정의했으니 사용해보는건 어떨까요?😀

2021-12-29 11:06 UTC, wonhee009 commented on GradeManager/GradeManager.swift
> +        guard let menuNum = Int(input), 1..<GradeManagingMenu.allCases.count ~= menuNum else {
`GradeManagingMenu`에 'O: 시작'이라는 메뉴가 추가된다면 어떻게 될까요?🤔
저는 두 가지 흐름 정도가 생각나는데요.

- `exit`는 메뉴인가?라는 생각이 듭니다. exit를 제외한 케이스들은 성적/학생 데이터를 조작하는데 exit는 매니저의 흐름을 관리한다는 생각이 듭니다. 따라서 exit는 따로 정의해야하지 않을까?라는 생각이 들었구요.
- String rawValue를 활용할 수도 있을거 같습니다. 

---

`exit`를 따로 관리하여 Menu enum에서 제외하던 String rawValue를 사용하던
```swift
GradeManagingMenu.allCases.contains(where: { $0.rawValue == menuNum })
```
이런 식을 활용할 수 있지 않을까 생각이 듭니다.

이런 방식들이 갖는 장점으로는 이후에 메뉴의 번호 변경이나 메뉴의 추가에 좀 더 유연하게 대처할 수 있다고 생각합니다.☺️

2021-12-29 11:07 UTC, wonhee009 commented on GradeManager/GradeManager.swift
> +struct GradeManager{
굉장히 많은 고민을 해보셨네요👍
저도 동일한 이유로 질문했습니다 굿굿👍

2021-12-29 11:08 UTC, wonhee009 commented on GradeManager/GradeManager.swift
> +    }
`perform`이나 `Action`은 동일한 의미인거 같은데요. 하나만 남아 있어도 될거 같습니다!

2021-12-29 11:33 UTC, liam-777 commented on GradeManager/GradeManager.swift
> +        guard let input = input, !input.isEmpty else {
아 모든 곳에 적용하는걸 실수했네요 😅
꼼꼼하게 봐주셔서 감사합니다. 저도 더 꼼꼼하게 확인하겠습니다.

2021-12-29 12:54 UTC, liam-777 commented on GradeManager/GradeManager.swift
> +        guard let menuNum = Int(input), 1..<GradeManagingMenu.allCases.count ~= menuNum else {
아하 좋은 피드백 감사합니다.

`exit`을 분리해서 `ProgramState` enum에서 관리하도록 하였습니다!
`contains(where:)`은 인지하지 못하고 있던 메서드인데 알려주셔서 감사합니다😁

2021-12-30 01:03 UTC, wonhee009 approved these changes
@liam-777 수고하셨습니다!👍
다음 스텝도 화이팅!

2021-12-30 01:04 UTC, merged